### ISSUE TITLE
Deliverables folder

### ISSUE THREAD

**Issue by cmd644** [oliveoil222/CS386-Project#12]
We should put a 'Deliverables' folder within our main branch, and we should not have this folder within any other branch. Lets figure out our branching first before we add this folder.

**Comment by dallonjarman** [comment]
Sounds good with me!

**Comment by cmd644** [comment]
Deliverable folder is made, @SamCain04 (SCRUM master for the week) should close this, since we now have the deliverables folder.

**Comment by SamCain04** [comment]
Yes sir. Well done everyone on this weeks tasks
