### ISSUE TITLE
Vote on restructuring the GitHub branches

### ISSUE THREAD

**Issue by cmd644** [oliveoil222/CS386-Project#13]
Instead of splitting up the branches by front, middle, and backend, let's take a Google style approach, detailed below:

Application Channels: stable, canary, dev

stable: least buggy channel, this is what we would deploy to the web application in "production"

canary: dev type channel with the newest features, this is where we test the features, this is our last chance to actually get the feature nailed down with very little bugs before merging into stable.

dev: most buggy channel with latest features, this is where we dump most of our commits, where we will primarily work. this branch is where we will build out our features.

Let's take a vote on restructuring like this, please add a comment on whether or not we should do it this way. I've given it some thought, and this might be a better way of doing it.

**Comment by oliveoil222** [comment]
This makes sense as long as we can have some labeling in the branches to keep it organized. I say we do this approach

**Comment by jjkagie** [comment]
This makes sense to me.

**Comment by SamCain04** [comment]
I agree, I think this approach is much more efficient.

**Comment by dallonjarman** [comment]
That works for me!

**Comment by hannahpenado** [comment]
Sounds good to me!

**Comment by dallonjarman** [comment]
@cmd644 wanted to check in and see if this is an issue we can resolve

**Comment by cmd644** [comment]
Yes, we can close it now... forgot to do it... make sure y'all update your forks of the main repo... you'll probably have to use something `git pull --all`
